# Generated by Django 4.1.7 on 2023-03-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
